#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install wget

mkdir -p /opt/cprof

wget -q -O- https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz | tar xzv -C /opt/cprof
