#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install ca-certificates gnupg curl

mkdir -p /etc/apt/keyrings
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

NODE_MAJOR="${NODE_VERSION:-21}"

echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list

apt-get -qq update
apt-get -y -qq --no-install-recommends install nodejs
