#!/bin/bash
# {:doc "Installs the latest version of Clojure (https://clojure.org/guides/install_clojure#_linux_instructions)"}

set -e

cd /tmp
curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
chmod +x linux-install.sh
sudo ./linux-install.sh
