#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install gnupg software-properties-common ca-certificates wget

wget -O- https://apt.releases.hashicorp.com/gpg | \
gpg --dearmor | \
tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
tee /etc/apt/sources.list.d/hashicorp.list

apt-get -qq update
apt-get -y -qq --no-install-recommends install terraform
