#!/bin/bash

set -e

curl -L -o jdk.tar.gz "https://download.java.net/java/GA/jdk20/bdc68b4b9cbc4ebcb30745c85038d91d/36/GPL/openjdk-20_linux-x64_bin.tar.gz"
tar -xzf jdk.tar.gz
rm jdk.tar.gz
mkdir -p /usr/lib/jvm
mv jdk-20 /usr/lib/jvm/
ln -s /usr/lib/jvm/jdk-20/bin/java /usr/local/bin/java
