#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install -y apt-transport-https ca-certificates curl software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get -qq update

apt-cache policy docker-ce

apt-get -y -qq --no-install-recommends install docker-ce

# The next step adds your user to the docker group, so that you can run Docker
# without using sudo. Please logout and login again afterwards:

usermod -aG docker ${USER}
