#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install -y apt-transport-https ca-certificates curl software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add

add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"

apt-get -qq update

apt-cache policy docker-ce

apt-get -y -qq --no-install-recommends docker-ce

# The next step adds your user to the docker group, so that you can run Docker
# without using sudo. Please logout and login again afterwards:

usermod -aG docker ${USER} && su - ${USER}
