#!/bin/bash

set -e

VERSION="${DATOMIC_VERSION:-1.0.7021}"

apt-get -qq update
apt-get -y -qq --no-install-recommends install ca-certificates curl unzip

curl -o datomic.zip https://datomic-pro-downloads.s3.amazonaws.com/$VERSION/datomic-pro-$VERSION.zip

unzip datomic.zip

mv "datomic-pro-$VERSION" /opt/datomic

rm datomic.zip

mkdir -p /opt/datomic/config
