#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install -y ca-certificates gnupg gpg-agent curl

GCSFUSE_REPO=gcsfuse-`lsb_release -c -s`
echo "deb https://packages.cloud.google.com/apt $GCSFUSE_REPO main" | tee /etc/apt/sources.list.d/gcsfuse.list
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

apt-get -qq update
apt-get -y -qq --no-install-recommends install gcsfuse
