#!/bin/bash

set -e

apt-get -qq update

apt-get -y -qq --no-install-recommends install curl

curl -LO "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"

apt-get -y -qq --no-install-recommends install ./google-chrome-stable_current_amd64.deb

rm google-chrome-stable_current_amd64.deb
