#!/bin/bash

set -e

VERSION="${GITHUB_ACTIONS_RUNNER_VERSION:2.311.0}"

DIR="/opt/github-actions-runner"

mkdir -p $DIR

curl -o "$DIR/actions-runner.tar.gz" "-L" "https://github.com/actions/runner/releases/download/v${VERSION}/actions-runner-linux-x64-${VERSION}.tar.gz"

(cd /opt/github-actions-runner && tar xzf ./actions-runner.tar.gz)
