#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install -y gpg-agent

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -

echo 'deb https://dl.yarnpkg.com/debian/ stable main' | tee /etc/apt/sources.list.d/yarn.list

apt-get -qq update

apt-get -y -qq --no-install-recommends install -y yarn
