#!/bin/bash

set -e

apt-get -qq update
apt-get -y -qq --no-install-recommends install -y ca-certificates gnupg curl

echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

apt-get -qq update
apt-get -y -qq --no-install-recommends install google-cloud-cli
